/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_windivert_pni_WinDivertDataNetwork */
#ifndef _Included_io_vproxy_windivert_pni_WinDivertDataNetwork
#define _Included_io_vproxy_windivert_pni_WinDivertDataNetwork
#ifdef __cplusplus
extern "C" {
#endif

struct WinDivertDataNetwork;
typedef struct WinDivertDataNetwork WinDivertDataNetwork;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(WinDivertDataNetwork, WinDivertDataNetwork *)
PNIBufExpand(WinDivertDataNetwork, WinDivertDataNetwork, 8)

struct WinDivertDataNetwork {
    uint32_t ifIdx;
    uint32_t subIfIdx;
};

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_windivert_pni_WinDivertDataNetwork
// metadata.generator-version: pni 21.0.0.17
// sha256:295376a426c4ebf750e094dfa8e82ccb8b059015f366bff0d5a977fca49b40b6
