/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_windivert_pni_WinDivert */
#ifndef _Included_io_vproxy_windivert_pni_WinDivert
#define _Included_io_vproxy_windivert_pni_WinDivert
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "io_vproxy_windivert_pni_WinDivertAddress.h"

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void * JNICALL WinDivertOpen(char * filter, int32_t layer, int16_t priority, uint64_t flags);
JNIEXPORT uint8_t JNICALL WinDivertRecv(void * handle, void * pPacket, uint32_t packetLen, uint32_t* pRecvLen, WinDivertAddress * pAddr);
JNIEXPORT uint8_t JNICALL WinDivertSend(void * handle, void * pPacket, uint32_t packetLen, uint32_t* pSendLen, WinDivertAddress * pAddr);
JNIEXPORT uint8_t JNICALL WinDivertClose(void * handle);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_windivert_pni_WinDivert
// metadata.generator-version: pni 21.0.0.17
// sha256:829b67f6e582932e7176c732ca0e039ea41be81bcd99cdd281d3dfe5ab678dda
