/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_windivert_pni_WinDivertData */
#ifndef _Included_io_vproxy_windivert_pni_WinDivertData
#define _Included_io_vproxy_windivert_pni_WinDivertData
#ifdef __cplusplus
extern "C" {
#endif

union WinDivertData;
typedef union WinDivertData WinDivertData;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "io_vproxy_windivert_pni_WinDivertDataNetwork.h"
#include "io_vproxy_windivert_pni_WinDivertDataFlow.h"
#include "io_vproxy_windivert_pni_WinDivertDataSocket.h"
#include "io_vproxy_windivert_pni_WinDivertDataReflect.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(WinDivertData, WinDivertData *)
PNIBufExpand(WinDivertData, WinDivertData, 64)

union WinDivertData {
    WinDivertDataNetwork network;
    WinDivertDataFlow flow;
    WinDivertDataSocket socket;
    WinDivertDataReflect reflect;
    uint8_t reserved0[64];
};

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_windivert_pni_WinDivertData
// metadata.generator-version: pni 21.0.0.17
// sha256:b4687ce7a3589af5d24b27d79797f0ce1c188036215ba6994218e713bd6bbd03
