/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_windivert_pni_WinDivertDataSocket */
#ifndef _Included_io_vproxy_windivert_pni_WinDivertDataSocket
#define _Included_io_vproxy_windivert_pni_WinDivertDataSocket
#ifdef __cplusplus
extern "C" {
#endif

struct WinDivertDataSocket;
typedef struct WinDivertDataSocket WinDivertDataSocket;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(WinDivertDataSocket, WinDivertDataSocket *)
PNIBufExpand(WinDivertDataSocket, WinDivertDataSocket, 64)

struct WinDivertDataSocket {
    uint64_t endpointId;
    uint64_t parentEndpointId;
    uint32_t processId;
    uint32_t localAddr[4];
    uint32_t remoteAddr[4];
    uint16_t localPort;
    uint16_t remotePort;
    uint8_t protocol;
};

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_windivert_pni_WinDivertDataSocket
// metadata.generator-version: pni 21.0.0.17
// sha256:abde4ed2ab717a8fb3d8cba20739fcc9f7a2c0d38e1b7af52f996411138eef38
