/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_windivert_pni_WinDivertDataReflect */
#ifndef _Included_io_vproxy_windivert_pni_WinDivertDataReflect
#define _Included_io_vproxy_windivert_pni_WinDivertDataReflect
#ifdef __cplusplus
extern "C" {
#endif

struct WinDivertDataReflect;
typedef struct WinDivertDataReflect WinDivertDataReflect;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(WinDivertDataReflect, WinDivertDataReflect *)
PNIBufExpand(WinDivertDataReflect, WinDivertDataReflect, 32)

struct WinDivertDataReflect {
    int64_t timestamp;
    uint32_t processId;
    int32_t layer;
    uint64_t flags;
    int16_t priority;
};

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_windivert_pni_WinDivertDataReflect
// metadata.generator-version: pni 21.0.0.17
// sha256:f93022e92ccf8ee3b2d072c94021b1edb0bd31a213c9c4714bad7066cc3d3ac5
