/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_windivert_pni_WinDivertDataFlow */
#ifndef _Included_io_vproxy_windivert_pni_WinDivertDataFlow
#define _Included_io_vproxy_windivert_pni_WinDivertDataFlow
#ifdef __cplusplus
extern "C" {
#endif

struct WinDivertDataFlow;
typedef struct WinDivertDataFlow WinDivertDataFlow;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(WinDivertDataFlow, WinDivertDataFlow *)
PNIBufExpand(WinDivertDataFlow, WinDivertDataFlow, 64)

struct WinDivertDataFlow {
    uint64_t endpointId;
    uint64_t parentEndpointId;
    uint32_t processId;
    uint32_t localAddr[4];
    uint32_t remoteAddr[4];
    uint16_t localPort;
    uint16_t remotePort;
    uint8_t protocol;
};

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_windivert_pni_WinDivertDataFlow
// metadata.generator-version: pni 21.0.0.17
// sha256:e224a491d6824e4c4838b781a63c0dd6972e733aa1d4c7c9d0982518292f7552
