/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_windivert_pni_ProfileAPI */
#ifndef _Included_io_vproxy_windivert_pni_ProfileAPI
#define _Included_io_vproxy_windivert_pni_ProfileAPI
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "profileapi.h"

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT uint8_t JNICALL QueryPerformanceFrequency(int64_t * lpFrequency);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_windivert_pni_ProfileAPI
// metadata.generator-version: pni 21.0.0.17
// sha256:30d6da23f4a53c6cc94cb50694cd226028836c9e76650f0661d6df5bac1a2c07
